### ISSUE TITLE
How to preprocess the Acronym dataset for training?

### ISSUE THREAD

**Issue by zhanghm1995** [princeton-computational-imaging/gensdf#1]
Hi, thanks for sharing this amazing work.

When I want to train GenSDF from scratch, I find the downloaded Acronym dataset is in `.h5` file format by default, while GenSDF needs `.csv` files.

I find the `data/preprocessing/preprocess_script.py` script contains the processing pipeline, however, this script requires the dataset in `model.obj` file format. So I'm not sure how to preprocess the Acronym dataset for training.

I would appreciate it if you give some hints or codes on preprocessing this dataset.

**Comment by gene-chou** [comment]
Here is a snippet from the acronym [project page](https://sites.google.com/nvidia.com/graspdataset):
```
> import h5py
> import numpy as np
> grasps = h5py.File('WineGlass_2d89d2b3b6749a9d99fbba385cc0d41d_0.0024652679182251653.h5', 'r')
> grasps.visititems(print)
> grasps['object/file'][()]
'meshes/WineGlass/2d89d2b3b6749a9d99fbba385cc0d41d.obj'
> grasps['grasps/transforms'].shape
(2000, 4, 4)
```
You should be able to extract `.obj` files from the above. Alternatively, you could also follow the preprocessing steps of DeepSDF to obtain SDF values from ShapeNet. The csv files I used are simply lines of xyz coordinates and their signed distance values, so you could easily convert them from npz files, for instance.

**Comment by zhanghm1995** [comment]
Thanks for your reply.

However, I cannot find the exact code to extract the `.obj` file from the above snippet. The `grasps['object/file'][()]` returns the `btypes` type variable representing the obj file name, while the `grasps['grasps/transforms']` returns the transformation information. I'm not familiar with this. 😞 

In addition, when applying the data preprocessing, we also need to sample the query points in the volume space for unlabeled data just like you have mentioned in your paper. And it also involves some other details, so I'm not sure whether my processing is the same as yours. Could you provide your processing code to reproduce this work?

**Comment by gene-chou** [comment]
For preprocessing meshes, I have provided the C++ code in the `data/preprocessing` folder. For preprocessing unlabeled data (i.e. point clouds), check out `dataloader/unlabeled_ds.py`.

**Comment by zhanghm1995** [comment]
OK, thank you very much for your response.
