### ISSUE TITLE
About the acronym dataset preprocessing

### ISSUE THREAD

**Issue by list17** [princeton-computational-imaging/gensdf#2]
Hi, I am not familiar with the acronym dataset and I have some questions about how to preprocess the dataset. I did not find the mesh in the original acronym dataset(1.6GB, .h5 files). But I found we need to download the ShapeNetSem dataset if we want to use the full acronym dataset.

https://github.com/NVlabs/acronym/blob/d78431f06de3965de1b229510102d118ea8d9de1/README.md?plain=1#L107-L114

So all the meshes we use for training are from the ShapeNetSem dataset?
If so, whether the preprocessing steps are as follows?
1. Get the model names from .h5 files in the acronym dataset.
2. Get the meshes from the ShapeNetSem dataset according to the names and create the watertight versions by the above [steps](https://github.com/NVlabs/acronym/blob/d78431f06de3965de1b229510102d118ea8d9de1/README.md?plain=1#L111) in the acronym GitHub page.
3. Recenter and normalize the watertight meshes from the ShapeNetSem dataset.
4. Sample points and calculate the corresponding SDF values by your script.

I want to know whether the preprocessing steps are right. Thank you.

**Comment by gene-chou** [comment]
Acronym is a subset of ShapeNet, so you can directly work with ShapeNet if you have the meshes downloaded. An option is to run the preprocessing code (as you linked above) to create watertight meshes, and discard all meshes that cannot be watertight or encounter other issues. This is also a great repo [https://github.com/marian42/mesh_to_sdf](https://github.com/marian42/mesh_to_sdf) that helps with preprocessing and approximates the values of non-watertight meshes. Then, for preprocessing unsupervised samples, you can use my code. Hope this helps.

**Comment by list17** [comment]
Thank you so much. That's helpful.
