### ISSUE TITLE
Recommended GPU for running demo

### ISSUE THREAD

**Issue by NiluK** [princeton-computational-imaging/gensdf#3]
Hello, what is the recommended GPU for running the Demo?

I tried it on an AWS EC2 G4dn instance which uses a T4 GPU but that failed pretty hard and gave me  this error

(sdf) ubuntu@ip-172-31-86-203:~/projects/gensdf$ python test_single.py -f data/acronym/Bear/52f9a230c400bddd55330ea4156a425f/sdf_data.csv -o . 

gensdf semi-supervised stage 2, loading from meta-learning stage pretrained model...
/home/ubuntu/projects/gensdf/model/gensdf/model.py:261: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  positions = np.vstack(map(np.ravel, g))
Traceback (most recent call last):
  File "/home/ubuntu/projects/gensdf/test_single.py", line 100, in <module>
    main()
  File "/home/ubuntu/projects/gensdf/test_single.py", line 51, in main
    model.reconstruct(model, {'point_cloud':f, 'mesh_name':"loaded_file"}, eval_dir="single_recon", testopt=True, sampled_points=sampled_points) 
  File "/home/ubuntu/projects/gensdf/model/gensdf/model.py", line 196, in reconstruct
    model = self.fast_opt(model, sampled_pc, num_iterations=800)
  File "/home/ubuntu/projects/gensdf/model/gensdf/model.py", line 218, in fast_opt
    xyz_full, gt_pt_full = self.fast_preprocess(full_pc)
  File "/home/ubuntu/projects/gensdf/model/gensdf/model.py", line 295, in fast_preprocess
    dists = torch.cdist(xyz, pc)
  File "/opt/conda/envs/sdf/lib/python3.9/site-packages/torch/functional.py", line 1278, in cdist
    return _VF.cdist(x1, x2, p, None)  # type: ignore[attr-defined]
RuntimeError: [enforce fail at alloc_cpu.cpp:73] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 19800000000 bytes. Error code 12 (Cannot allocate memory)

I read the paper and the paper said it was trained on a single A100 GPU which is great, but that's also $32 per hour. 

I will try and see if it works some smaller GPUS

**Comment by gene-chou** [comment]
This is related to ram not gpu memory. Consider increasing your ram (cpu memory) of your instance or reduce the number of points in line 42 of the file (e.g. `sampled_points=5000`)

**Comment by NiluK** [comment]
Ah yep! Thanks.

Upgrading to G4DN 2X Large works great.

Going to try it out with some point clouds now. 

Thanks!
